# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(258, 219)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_openfile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openfile.setGeometry(QtCore.QRect(10, 10, 75, 20))
        self.pushButton_openfile.setObjectName("pushButton_openfile")
        self.label_filepath = QtWidgets.QLabel(self.centralwidget)
        self.label_filepath.setGeometry(QtCore.QRect(10, 30, 231, 20))
        self.label_filepath.setObjectName("label_filepath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 47, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 47, 20))
        self.label_3.setObjectName("label_3")
        self.comboBox_students = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_students.setGeometry(QtCore.QRect(40, 60, 69, 22))
        self.comboBox_students.setObjectName("comboBox_students")
        self.comboBox_day = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_day.setGeometry(QtCore.QRect(40, 90, 69, 22))
        self.comboBox_day.setObjectName("comboBox_day")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 47, 20))
        self.label_4.setObjectName("label_4")
        self.comboBox_data = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_data.setGeometry(QtCore.QRect(40, 120, 69, 22))
        self.comboBox_data.setObjectName("comboBox_data")
        self.label_data = QtWidgets.QLabel(self.centralwidget)
        self.label_data.setGeometry(QtCore.QRect(40, 150, 71, 20))
        self.label_data.setObjectName("label_data")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 47, 20))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 258, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ReadExcel"))
        self.pushButton_openfile.setText(_translate("MainWindow", "開啟檔案"))
        self.label_filepath.setText(_translate("MainWindow", "---"))
        self.label_2.setText(_translate("MainWindow", "學生"))
        self.label_3.setText(_translate("MainWindow", "天數"))
        self.label_4.setText(_translate("MainWindow", "內容"))
        self.label_data.setText(_translate("MainWindow", "----"))
        self.label_6.setText(_translate("MainWindow", "分數"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
